### ISSUE TITLE
This project finished yet?

### ISSUE THREAD

**Issue by lovechang1986** [innot/AdvPiStepper#2]
Hi, as title, this project is finished?

I has a 42 stepper moter and dm422 stepper controler, can i use this scripts to run the moter?

**Comment by innot** [comment]
Unfortunately the project is not finished.

Due to a growing family and some other issues I did not have time to work on this project.
I do plan to return to it eventually, as I need it for a larger project of mine - but I can't give any timeline at the moment.

With regard to the dm422 controller: It should work with the DriverStepDirGeneric driver as it supports a STEP/DIR interface.
